@startmindmap

caption https://github.com/cyber-mint/c4devs
title Cryptography for Developers

*[#lightgreen] Cryptography

 *_ Secrets
  * Keys
****:Key Stretching
 salt + pepper;

*****[#lightgreen]: **PBKDF2**
<code>
    kdf = PBKDF2(
        algorithm=hashes.SHA256(),
        length=32,
        salt=salt,
        iterations=390000,
        password='my password' )
</code>
;
    * HKDF
  * Tokens
   * JWT

 *_ Ciphers <<rose>>
  * Substitution
  * Stream
  * Block
   *_ concepts
    * Fiestal
   * Symmetric
    * Cypher Block Chaining
    * AES
  * Asymmetric
   *_ sign & verify
   * RSA
   * ECDSA
  *_ certificates
   *_ formats
    * PKCS#1-formatting keys & hashes for RSA
    * ANS.1.BER
    * X.509
    * PKCS#7-store CRTs & CRLs
    * DER-crt encoding
    * PEM-binary crt encoding in base 64
    * PKCS#12 - store CRTs & CRLs
   * Certificate Authority
   * Certificate Revocation
   * Certificate Signing Request
  *_ key exchange
   * RSA
   * Eliptic Curve
    * ECDHE
   * Diffie Helman

 *_ Random Numbers
  * Salt
  * Initial Vector
  * NONCE 
 *_ One Way Functions
  * hash
   * MD5
   * SHA1
   *[#FFBBCC] SHA256
  * hmac
 *_ Transport Layer Security
  * SSL/TLS
  * TLS Handshake
  * CA certificates
  * Cipher Suites 
  * Session Keys
  * HTTPS encryption

left side

--_ Mathematics
  * XOR
  * Modulus mathematics
  * Prime Numbers
  * Eliptic Curves

--_ Python
  * hashlib
  * pyopenssl

--_ Concepts
  * Privacy
  * Non-Repudiation
  * Confidentiality
  * Integrity


--_ Linux
  * base64
  * xxd
  * openssl
   * self-signed certificates
  * gpg
   * key management
   * key servers
   * chain of trust
  * sha256sum
  *_ ssh
   * ssh-keygen
   * git

--_ Tools & Services
  * LetsEncrypt
  * openVPN

--_ HDD & Data
  *_ Linux
   * LUKS HDD Encryption
  *_ Windows
   * BitLocker HDD Encryption
  *_ postgresql
   * pg_crypto

header
 Creative Commons Zero (CC)
endheader

center footer Cyber-Mint (Pty) Ltd

' legend right
'   Short
'   legend
' endlegend

@endmindmap